---
- name: Install autossh
  yum:
    name: autossh
  become: true

- name: Set up autossh systemd service
  template:
    dest: /etc/systemd/system/autossh.service
    src: autossh.service.template
  become: true
  notify: Restart autossh service

- name: Start and enable autossh service
  tags: notest
  systemd:
    daemon_reload: true
    enabled: true
    name: autossh
    state: started
  become: true
