---
- name: Reload systemd
  systemd:
    daemon_reload: true
  become: true
  when: notest is not defined

- name: Restart autossh service
  service:
    name: autossh
    state: restarted
  become: true
  when: notest is not defined
